"use client";

import React, { useState, useEffect, useRef } from "react";

interface LivePreviewProps {
  code: string;
  language?: "html" | "react";
}

type DeviceType = "fit" | "desktop" | "laptop" | "tablet" | "mobile";
type Orientation = "portrait" | "landscape";

const DEVICE_PRESETS: Record<
  DeviceType,
  { width: number; height: number; label: string }
> = {
  fit: { width: 0, height: 0, label: "Fit" },
  desktop: { width: 1920, height: 1080, label: "Desktop" },
  laptop: { width: 1440, height: 900, label: "Laptop" },
  tablet: { width: 768, height: 1024, label: "Tablet" },
  mobile: { width: 375, height: 667, label: "Mobile" },
};

/**
 * Build an iframe document for React/JSX code generated by Gemini.
 * The Gemini prompt asks for: a single default-exported functional component,
 * no imports beyond React, Tailwind utility classes for styling.
 *
 * We wrap the code so it works inside a sandboxed iframe by:
 *   - injecting React 18 + ReactDOM + Babel-standalone + Tailwind CDN
 *   - stripping any `import ... from "react"` lines (Babel-standalone won't
 *     resolve them)
 *   - rewriting `export default function NAME` (or `export default NAME`) so
 *     the component name is left as a top-level binding, then mounting it via
 *     ReactDOM.createRoot.
 */
function buildReactDocument(rawCode: string): string {
  let code = rawCode;

  // Remove import/require lines — Babel-standalone runs in classic-script mode
  // and can't resolve them. React/ReactDOM are exposed as globals below.
  code = code.replace(/^\s*import\s+[^;]+;?\s*$/gm, "");
  code = code.replace(/^\s*const\s+\w+\s*=\s*require\([^)]+\);?\s*$/gm, "");

  // Find the default-exported component name and strip the `export default`
  // marker so the binding stays in the surrounding scope.
  let componentName: string | null = null;
  const defaultFnMatch = code.match(/export\s+default\s+function\s+(\w+)/);
  if (defaultFnMatch) {
    componentName = defaultFnMatch[1];
    code = code.replace(/export\s+default\s+function/, "function");
  } else {
    const defaultIdentMatch = code.match(/export\s+default\s+(\w+)\s*;?/);
    if (defaultIdentMatch) {
      componentName = defaultIdentMatch[1];
      code = code.replace(/export\s+default\s+\w+\s*;?/, "");
    }
  }

  // Fallback: anonymous arrow exports like `export default () => (...)`
  if (!componentName) {
    componentName = "GeneratedComponent";
    code = code.replace(
      /export\s+default\s+/,
      `const ${componentName} = `
    );
  }

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="Content-Security-Policy" content="script-src 'unsafe-inline' 'unsafe-eval' https:; style-src 'unsafe-inline' https:;">
  <script src="https://cdn.tailwindcss.com"></script>
  <script crossorigin src="https://unpkg.com/react@18/umd/react.production.min.js"></script>
  <script crossorigin src="https://unpkg.com/react-dom@18/umd/react-dom.production.min.js"></script>
  <script src="https://unpkg.com/@babel/standalone/babel.min.js"></script>
  <style>* { box-sizing: border-box; } body { margin: 0; font-family: system-ui, -apple-system, sans-serif; }</style>
</head>
<body>
  <div id="root"></div>
  <script>
    const originalLog = console.log;
    console.log = function(...args) {
      originalLog.apply(console, args);
      window.parent.postMessage({ type: 'console', data: args.map(a => String(a)).join(' ') }, '*');
    };
    window.onerror = function(msg, url, line) {
      window.parent.postMessage({ type: 'error', data: 'Error: ' + msg + ' at line ' + line }, '*');
      return false;
    };
  </script>
  <script type="text/babel" data-presets="env,react">
    ${code}
    try {
      const root = ReactDOM.createRoot(document.getElementById('root'));
      root.render(React.createElement(${componentName}));
    } catch (err) {
      document.getElementById('root').innerHTML =
        '<pre style="color:#b00;padding:16px;white-space:pre-wrap;font-family:monospace;">' +
        'Render error: ' + (err && err.message ? err.message : String(err)) +
        '</pre>';
      window.parent.postMessage({ type: 'error', data: String(err) }, '*');
    }
  </script>
</body>
</html>`;
}

function buildHtmlDocument(rawCode: string): string {
  if (rawCode.includes("<!DOCTYPE") || rawCode.includes("<html")) {
    return rawCode;
  }
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="Content-Security-Policy" content="script-src 'unsafe-inline' 'unsafe-eval' https:; style-src 'unsafe-inline' https:;">
  <script src="https://cdn.tailwindcss.com"></script>
  <style>* { margin: 0; padding: 0; box-sizing: border-box; } body { font-family: system-ui, -apple-system, sans-serif; }</style>
</head>
<body>
${rawCode}
<script>
  const originalLog = console.log;
  console.log = function(...args) {
    originalLog.apply(console, args);
    window.parent.postMessage({ type: 'console', data: args.map(a => String(a)).join(' ') }, '*');
  };
  window.onerror = function(msg, url, line) {
    window.parent.postMessage({ type: 'error', data: 'Error: ' + msg + ' at line ' + line }, '*');
    return false;
  };
</script>
</body>
</html>`;
}

export default function LivePreview({ code, language = "html" }: LivePreviewProps) {
  const [device, setDevice] = useState<DeviceType>("fit");
  const [orientation, setOrientation] = useState<Orientation>("portrait");
  const [manualZoom, setManualZoom] = useState<number | null>(null);
  const [containerSize, setContainerSize] = useState({
    width: 800,
    height: 600,
  });
  const [consoleOutput, setConsoleOutput] = useState<string[]>([]);
  const [showConsole, setShowConsole] = useState(false);
  const [refreshTick, setRefreshTick] = useState(0);
  const iframeRef = useRef<HTMLIFrameElement>(null);
  const containerRef = useRef<HTMLDivElement>(null);

  // Track container size so "Fit" mode can size the iframe to fill available space.
  useEffect(() => {
    if (!containerRef.current) return;
    const el = containerRef.current;
    const update = () => {
      setContainerSize({
        width: Math.max(320, el.clientWidth - 48),
        height: Math.max(240, el.clientHeight - 48),
      });
    };
    update();
    const observer = new ResizeObserver(update);
    observer.observe(el);
    return () => observer.disconnect();
  }, []);

  const getDeviceDimensions = () => {
    if (device === "fit") {
      return { width: containerSize.width, height: containerSize.height };
    }
    const preset = DEVICE_PRESETS[device];
    if (orientation === "landscape") {
      return { width: preset.height, height: preset.width };
    }
    return { width: preset.width, height: preset.height };
  };

  const dimensions = getDeviceDimensions();

  const autoScale = Math.min(
    containerSize.width / dimensions.width,
    containerSize.height / dimensions.height,
    1
  );

  const scale = manualZoom ?? autoScale;

  const selectDevice = (next: DeviceType) => {
    setDevice(next);
    setManualZoom(null);
  };

  const toggleOrientation = () => {
    setOrientation((prev) => (prev === "portrait" ? "landscape" : "portrait"));
    setManualZoom(null);
  };

  useEffect(() => {
    if (!iframeRef.current) return;

    const iframe = iframeRef.current;
    const iframeDoc = iframe.contentDocument || iframe.contentWindow?.document;

    if (!iframeDoc) return;

    const htmlContent =
      language === "react"
        ? buildReactDocument(code)
        : buildHtmlDocument(code);

    iframeDoc.open();
    iframeDoc.write(htmlContent);
    iframeDoc.close();
  }, [code, language, refreshTick]);

  useEffect(() => {
    const handleMessage = (event: MessageEvent) => {
      if (event.data.type === "console" || event.data.type === "error") {
        setConsoleOutput((prev) => [...prev, event.data.data]);
        if (event.data.type === "error") {
          setShowConsole(true);
        }
      }
    };

    window.addEventListener("message", handleMessage);
    return () => window.removeEventListener("message", handleMessage);
  }, []);

  const handleRefresh = () => {
    setConsoleOutput([]);
    setRefreshTick((t) => t + 1);
  };

  const handleOpenInNewWindow = () => {
    const newWindow = window.open("", "_blank");
    if (!newWindow) return;
    const htmlContent =
      language === "react" ? buildReactDocument(code) : buildHtmlDocument(code);
    newWindow.document.open();
    newWindow.document.write(htmlContent);
    newWindow.document.close();
  };

  return (
    <div className="flex h-full flex-col bg-[#0A0A0A]">
      <div className="flex items-center justify-between border-b border-[#2E2E2E] bg-[#1A1A1A] px-4 py-2">
        <div className="flex items-center gap-2">
          {Object.entries(DEVICE_PRESETS).map(([key, preset]) => (
            <button
              key={key}
              onClick={() => selectDevice(key as DeviceType)}
              className={`rounded-lg px-3 py-1.5 text-xs font-semibold transition-all ${
                device === key
                  ? "bg-white text-[#0A0A0A]"
                  : "bg-[#2E2E2E] text-[#A0A0A0] hover:bg-white/10 hover:text-white"
              }`}
              title={`${preset.label} (${preset.width}x${preset.height})`}
            >
              {preset.label}
            </button>
          ))}

          {device !== "desktop" && device !== "fit" && (
            <button
              onClick={toggleOrientation}
              className="ml-2 rounded-lg bg-[#2E2E2E] p-2 text-white transition-all hover:bg-white/10"
              title="Toggle Orientation"
            >
              <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15"
                />
              </svg>
            </button>
          )}
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={() => setShowConsole(!showConsole)}
            className="rounded-lg bg-[#2E2E2E] px-3 py-1.5 text-xs font-semibold text-white transition-all hover:bg-white/10"
          >
            Console {consoleOutput.length > 0 && `(${consoleOutput.length})`}
          </button>

          <button
            onClick={handleRefresh}
            className="rounded-lg bg-[#2E2E2E] p-2 text-white transition-all hover:bg-white/10"
            title="Refresh Preview"
          >
            <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15"
              />
            </svg>
          </button>

          <button
            onClick={handleOpenInNewWindow}
            className="rounded-lg bg-[#2E2E2E] p-2 text-white transition-all hover:bg-white/10"
            title="Open in New Window"
          >
            <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14"
              />
            </svg>
          </button>

          <div className="flex items-center gap-1 rounded-lg bg-[#2E2E2E] px-1 py-0.5">
            <button
              onClick={() =>
                setManualZoom((z) =>
                  Math.max(0.1, +((z ?? autoScale) - 0.1).toFixed(2))
                )
              }
              className="rounded px-1.5 py-0.5 text-xs text-white hover:bg-white/10"
              title="Zoom out"
            >
              −
            </button>
            <span className="min-w-14 text-center text-xs tabular-nums text-[#A0A0A0]">
              {Math.round(scale * 100)}%
            </span>
            <button
              onClick={() =>
                setManualZoom((z) =>
                  Math.min(2, +((z ?? autoScale) + 0.1).toFixed(2))
                )
              }
              className="rounded px-1.5 py-0.5 text-xs text-white hover:bg-white/10"
              title="Zoom in"
            >
              +
            </button>
            {manualZoom !== null && (
              <button
                onClick={() => setManualZoom(null)}
                className="rounded px-1.5 py-0.5 text-xs text-[#FF6B00] hover:bg-white/10"
                title="Reset to auto-fit"
              >
                Auto
              </button>
            )}
          </div>
          <span className="text-xs text-[#666666] tabular-nums">
            {Math.round(dimensions.width)} × {Math.round(dimensions.height)}
          </span>
        </div>
      </div>

      <div ref={containerRef} className="flex-1 overflow-auto bg-[#0A0A0A] p-6">
        <div
          className="mx-auto bg-white shadow-2xl"
          style={{
            width: dimensions.width,
            height: dimensions.height,
            transform: `scale(${scale})`,
            transformOrigin: "top center",
          }}
        >
          <iframe
            ref={iframeRef}
            title="Live Preview"
            sandbox="allow-scripts allow-same-origin allow-forms"
            className="h-full w-full border-0"
          />
        </div>
      </div>

      {showConsole && (
        <div className="border-t border-[#2E2E2E] bg-[#1A1A1A] p-4">
          <div className="mb-2 flex items-center justify-between">
            <h3 className="text-sm font-semibold text-white">Console Output</h3>
            <button
              onClick={() => setConsoleOutput([])}
              className="text-xs text-[#A0A0A0] hover:text-white"
            >
              Clear
            </button>
          </div>
          <div className="max-h-32 overflow-auto rounded-lg bg-[#0A0A0A] p-3 font-mono text-xs text-white">
            {consoleOutput.length === 0 ? (
              <div className="text-[#666666]">No console output</div>
            ) : (
              consoleOutput.map((output, i) => (
                <div key={i} className="py-1">
                  &gt; {output}
                </div>
              ))
            )}
          </div>
        </div>
      )}
    </div>
  );
}
